package com.soccermanager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path="/match")
public class GameController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GameRepository gameRepository;

    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Game> getAllMatches() {
        // This returns a JSON or XML with the users
        return gameRepository.findAll();
    }
    @GetMapping(path="/findMatchHome")
    public @ResponseBody Iterable<Game> getHomeMatch(@RequestParam("homeTeamId") String home_team_api_id) {

        // This returns a JSON or XML with the users
        return gameRepository.findByHomeId(home_team_api_id);

    }
    @GetMapping(path="/findMatchAway")
    public @ResponseBody Iterable<Game> getAwayMatch(@RequestParam("awayTeamId") String away_team_api_id) {

        // This returns a JSON or XML with the users
        return gameRepository.findByAwayId(away_team_api_id);

    }
}
