package com.soccermanager;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping(path="/player")
public class PlayerController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PlayerRepository playerRepository;

    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Player> getAllPlayers() {
        // This returns a JSON or XML with the users
        return playerRepository.findAll();
    }
    @GetMapping(path="/findPlayer")
    public @ResponseBody Iterable<Player> getPlayer(@RequestParam("playerName") String playerName) {

        // This returns a JSON or XML with the users
        return playerRepository.findByName(playerName);

    }
}
